name: JMH CI

env:
  GITHUB_DEPLOY: 'true'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Run JMH Benchmark.
    timeout-minutes: 15
    continue-on-error: false

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        jdk: [ '17' ]
    outputs:
      sha-version: ${{ steps.sha-version.outputs.version }}

    steps:
      - name: Check out the source code
        uses: actions/checkout@v2

      - name: Download JDK ${{ matrix.java }}
        id: download-jdk
        uses: sormuras/download-jdk@v1
        with:
          feature: ${{ matrix.java }}

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: jdkfile
          java-version: ${{ env.JDK_VERSION }}
          jdkFile: ${{ env.JDK_FILE }}

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Create Version Number
        id: sha-version
        run: |
          SHA_VERSION=$(echo $GITHUB_SHA | cut -c1-7)
          echo "::set-output name=version::$SHA_VERSION"

      - name: Maven Build
        run: ./mvnw -B verify

      - name: Deploy to GitHub Packages
        if: env.GITHUB_DEPLOY == 'true' && runner.os == 'Linux'
        run: |
          ./mvnw --settings .mvn/settings.xml deploy
        env:
          GITHUB_USER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run JMH Benchmark
        if: success()
        run: |
          java -jar target/benchmarks.jar
          mkdir staging && cp target/benchmarks.jar staging

      - uses: actions/upload-artifact@v2.2.3
        if: env.GITHUB_DEPLOY != 'true'
        with:
          name: Package
          path: staging


  release:
    name: Release new version.
    needs: [ build ]
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ${{ matrix.os }}

    steps:
      - name: check
        run: |
          echo "The SHA version from build job: ${{ needs.build.outputs.sha-version }}"
       

       
