name: JMH Sample CI

env:
  GH_DEPLOY: 'false'

on:
  schedule:
    - cron: "0 0 * * 0"    
  push:
    branches: [ master ]  
  pull_request:
    branches: [ master ]

jobs:
  build:
   
    name: Run JMH Benchmark.
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
       matrix:
         os: [ubuntu-latest]
         java: ['11', '14']

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
      
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
      
    - name: Build with Maven
      if: env.GH_DEPLOY != 'true'
      run: ./mvnw -B verify
    
    - name: Deploy to GitHub Packages
      if: env.GH_DEPLOY == 'true'
      run: ./mvnw deploy -Dregistry=https://maven.pkg.github.com/${{ github.repository_owner }} -Dtoken=${{ secrets.GITHUB_TOKEN }}
      
    - name: Run JMH Benchmark
      if: success()
      run: |
         java -jar target/benchmarks.jar
         mkdir staging && cp target/benchmarks.jar staging
         
    - uses: actions/upload-artifact@v1
      if: env.GH_DEPLOY != 'true'
      with:
        name: Package
        path: staging      
