name: Release Drafter

on:
  push:
    branches:
      - main
  # pull_request event is required only for autolabeler
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [ opened, reopened, synchronize ]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Drafts next Release notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: config/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}